### ISSUE TITLE
[chore] application.yml 파일 수정 & 환경 변수 설정

### ISSUE THREAD

**Issue by drbug2000** [KUIT-Space/KUIT_Space_BackEnd#11]
## 📝 이슈 설명
프로젝트 application.yml 파일 설정
local과 dev환경 분리
환경변수 파일 수정

## ✅ 투두리스트
- [x] 프로젝트 application.yml 파일 설정
- DB 설정
- JPA설정
- GWT 설정
- 기타 등등 (web, port 등등)
- [x] application.yml / application-local.yml 분리
- [ ] CI/CD 환경변수 주입

**Comment by drbug2000** [comment]
application-local.yml 파일 포맷입니다.
개인 local 환경에서 파일 생성해서 자유롭게 수정해서 사용하시면 됩니다.
```
# application-local.yml
spring:
  config:
    activate:
      on-profile: "localPort"

server:
    port: 8080
---
spring:
  config:
    activate:
      on-profile: "localRDB"

  datasource:
      url:  ${DATASOURCE_URL_LOCAL}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
logging:
  level:
    org.hibernate.sql: debug
---
spring:
  config:
    activate:
      on-profile: "localMongoDB"
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}

---
spring:
  config:
    activate:
      on-profile: "localJPA"

  jpa:
    hibernate:
          ddl-auto: update        # table을 전부 drop했다가 다시 생성 -> 테스트용
    properties:
      hibernate:
        format_sql: true
        show_sql: true
---

spring:
  config:
    activate:
      on-profile: "localSecret"

secret:
  jwt-secret-key: ${JWT_SECRET_KEY:b237a73895f5e617b7364708413fff71c228721a5f8c84a7bb2a3b84f1bb1c23}
  jwt-expired-in: ${JWT_EXPIRED_IN:3600000}
---

```
